version: '3.8'

services:
  drop4crop-api:
    build:
      context: .
    environment:
      - DB_HOST=drop4crop-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=psql
      - DB_NAME=postgres
      - DB_PREFIX=postgresql+asyncpg
    ports:
      - 8015:8000
    depends_on:
        - drop4crop-db
    volumes:
      - ./app/:/app/app

  drop4crop-db:
    image: postgis/postgis:16-master
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psql
      - POSTGRES_DB=postgres
    ports:
      - 5443:5432
    volumes:
      - drop4crop-db-data:/var/lib/postgresql/data
      - ./rasters:/rasters

volumes:
  drop4crop-db-data:
