"""Add variables to layer country link

Revision ID: 18464dc541c6
Revises: e17f78d56126
Create Date: 2024-08-21 11:51:45.009556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '18464dc541c6'
down_revision: Union[str, None] = 'e17f78d56126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layercountrylink', sa.Column('var_wf', sa.Float(), nullable=True))
    op.add_column('layercountrylink', sa.Column('var_wfb', sa.Float(), nullable=True))
    op.add_column('layercountrylink', sa.Column('var_wfg', sa.Float(), nullable=True))
    op.add_column('layercountrylink', sa.Column('var_vwc', sa.Float(), nullable=True))
    op.add_column('layercountrylink', sa.Column('var_vwcb', sa.Float(), nullable=True))
    op.add_column('layercountrylink', sa.Column('var_vwcg', sa.Float(), nullable=True))
    op.add_column('layercountrylink', sa.Column('var_wdb', sa.Float(), nullable=True))
    op.add_column('layercountrylink', sa.Column('var_wdg', sa.Float(), nullable=True))
    op.drop_index('ix_layercountrylink_value', table_name='layercountrylink')
    op.create_index(op.f('ix_layercountrylink_var_vwc'), 'layercountrylink', ['var_vwc'], unique=False)
    op.create_index(op.f('ix_layercountrylink_var_vwcb'), 'layercountrylink', ['var_vwcb'], unique=False)
    op.create_index(op.f('ix_layercountrylink_var_vwcg'), 'layercountrylink', ['var_vwcg'], unique=False)
    op.create_index(op.f('ix_layercountrylink_var_wdb'), 'layercountrylink', ['var_wdb'], unique=False)
    op.create_index(op.f('ix_layercountrylink_var_wdg'), 'layercountrylink', ['var_wdg'], unique=False)
    op.create_index(op.f('ix_layercountrylink_var_wf'), 'layercountrylink', ['var_wf'], unique=False)
    op.create_index(op.f('ix_layercountrylink_var_wfb'), 'layercountrylink', ['var_wfb'], unique=False)
    op.create_index(op.f('ix_layercountrylink_var_wfg'), 'layercountrylink', ['var_wfg'], unique=False)
    op.drop_column('layercountrylink', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layercountrylink', sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_layercountrylink_var_wfg'), table_name='layercountrylink')
    op.drop_index(op.f('ix_layercountrylink_var_wfb'), table_name='layercountrylink')
    op.drop_index(op.f('ix_layercountrylink_var_wf'), table_name='layercountrylink')
    op.drop_index(op.f('ix_layercountrylink_var_wdg'), table_name='layercountrylink')
    op.drop_index(op.f('ix_layercountrylink_var_wdb'), table_name='layercountrylink')
    op.drop_index(op.f('ix_layercountrylink_var_vwcg'), table_name='layercountrylink')
    op.drop_index(op.f('ix_layercountrylink_var_vwcb'), table_name='layercountrylink')
    op.drop_index(op.f('ix_layercountrylink_var_vwc'), table_name='layercountrylink')
    op.create_index('ix_layercountrylink_value', 'layercountrylink', ['value'], unique=False)
    op.drop_column('layercountrylink', 'var_wdg')
    op.drop_column('layercountrylink', 'var_wdb')
    op.drop_column('layercountrylink', 'var_vwcg')
    op.drop_column('layercountrylink', 'var_vwcb')
    op.drop_column('layercountrylink', 'var_vwc')
    op.drop_column('layercountrylink', 'var_wfg')
    op.drop_column('layercountrylink', 'var_wfb')
    op.drop_column('layercountrylink', 'var_wf')
    # ### end Alembic commands ###
