"""Modify name of key

Revision ID: 24e71aed2baf
Revises: 35e93be09316
Create Date: 2024-08-05 16:00:15.152776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24e71aed2baf'
down_revision: Union[str, None] = '35e93be09316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('style', sa.Column('style', sa.JSON(), nullable=True))
    op.drop_column('style', 'parts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('style', sa.Column('parts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('style', 'style')
    # ### end Alembic commands ###
