"""Create style table

Revision ID: 35e93be09316
Revises: a73ec8695b2a
Create Date: 2024-08-05 15:52:24.947853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '35e93be09316'
down_revision: Union[str, None] = 'a73ec8695b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parts', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('iterator', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('iterator'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_style_id'), 'style', ['id'], unique=False)
    op.create_index(op.f('ix_style_iterator'), 'style', ['iterator'], unique=False)
    op.create_index(op.f('ix_style_name'), 'style', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_style_name'), table_name='style')
    op.drop_index(op.f('ix_style_iterator'), table_name='style')
    op.drop_index(op.f('ix_style_id'), table_name='style')
    op.drop_table('style')
    # ### end Alembic commands ###
