"""Add style to db

Revision ID: 7e5d045ffa35
Revises: 935c0dc4382d
Create Date: 2024-07-18 17:18:57.214468

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "7e5d045ffa35"
down_revision: Union[str, None] = "935c0dc4382d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "layer",
        sa.Column(
            "style_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("layer", "style_name")

    # ### end Alembic commands ###
