"""Add min max fields

Revision ID: a73ec8695b2a
Revises: f6c1133f0139
Create Date: 2024-08-05 13:51:03.731349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a73ec8695b2a'
down_revision: Union[str, None] = 'f6c1133f0139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('min_value', sa.Float(), nullable=True))
    op.add_column('layer', sa.Column('max_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layer', 'max_value')
    op.drop_column('layer', 'min_value')
    # ### end Alembic commands ###
