"""Add upload id field

Revision ID: ad7ab7b5bfb2
Revises: cce3c15810c6
Create Date: 2024-08-02 13:50:14.556074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ad7ab7b5bfb2'
down_revision: Union[str, None] = 'cce3c15810c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('upload_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layer', 'upload_id')
    # ### end Alembic commands ###
