"""Add uploaded date to layers

Revision ID: b5f16c9cced0
Revises: 7e5d045ffa35
Create Date: 2024-07-19 12:28:22.695277

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b5f16c9cced0"
down_revision: Union[str, None] = "7e5d045ffa35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "layer",
        sa.Column(
            "uploaded_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("layer", "uploaded_at")

    # ### end Alembic commands ###
