"""Add link table between country and layer

Revision ID: c517a7971f8b
Revises: 132a15529d53
Create Date: 2024-07-22 17:06:50.201315

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c517a7971f8b"
down_revision: Union[str, None] = "132a15529d53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "country", ["name"])
    op.create_unique_constraint(None, "country", ["id"])
    op.create_table(
        "layercountrylink",
        sa.Column("country_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("layer_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["country.id"],
        ),
        sa.ForeignKeyConstraint(
            ["layer_id"],
            ["layer.id"],
        ),
        sa.PrimaryKeyConstraint("country_id", "layer_id"),
    )
    op.create_index(
        op.f("ix_layercountrylink_value"),
        "layercountrylink",
        ["value"],
        unique=False,
    )
    op.add_column(
        "layer", sa.Column("global_average", sa.Float(), nullable=True)
    )
    op.create_index(
        op.f("ix_layer_global_average"),
        "layer",
        ["global_average"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_layer_global_average"), table_name="layer")
    op.drop_column("layer", "global_average")
    op.drop_constraint(None, "country", type_="unique")
    op.drop_constraint(None, "country", type_="unique")
    op.drop_index(
        op.f("ix_layercountrylink_value"), table_name="layercountrylink"
    )
    op.drop_table("layercountrylink")
    # ### end Alembic commands ###
