"""Add file upload management fields

Revision ID: cce3c15810c6
Revises: c517a7971f8b
Create Date: 2024-08-02 13:38:54.918182

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "cce3c15810c6"
down_revision: Union[str, None] = "c517a7971f8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "layer",
        sa.Column(
            "processing_has_started",
            sa.Boolean(),
            nullable=False,
            server_default="false",
        ),
    )
    op.add_column(
        "layer",
        sa.Column(
            "processing_completed_successfully",
            sa.Boolean(),
            nullable=False,
            server_default="false",
        ),
    )
    op.add_column(
        "layer",
        sa.Column(
            "processing_message",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    op.add_column(
        "layer",
        sa.Column("last_part_received_utc", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "layer",
        sa.Column(
            "all_parts_received",
            sa.Boolean(),
            nullable=False,
            server_default="false",
        ),
    )
    op.add_column("layer", sa.Column("parts", sa.JSON(), nullable=True))
    op.alter_column(
        "layer", "layer_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("layer", "crop", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "layer", "variable", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "layer", "variable", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "layer", "crop", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "layer", "layer_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("layer", "parts")
    op.drop_column("layer", "all_parts_received")
    op.drop_column("layer", "last_part_received_utc")
    op.drop_column("layer", "processing_message")
    op.drop_column("layer", "processing_completed_successfully")
    op.drop_column("layer", "processing_has_started")
    # ### end Alembic commands ###
