"""Create relationship with Layer <-> Style

Revision ID: e17f78d56126
Revises: 24e71aed2baf
Create Date: 2024-08-05 16:42:53.089162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e17f78d56126'
down_revision: Union[str, None] = '24e71aed2baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('style_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'layer', 'style', ['style_id'], ['id'])
    op.drop_column('layer', 'style_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('style_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'layer', type_='foreignkey')
    op.drop_column('layer', 'style_id')
    # ### end Alembic commands ###
