"""Remove fields for chunked upload

Revision ID: f6c1133f0139
Revises: 23f1f5fa5ab0
Create Date: 2024-08-05 11:09:38.095030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6c1133f0139'
down_revision: Union[str, None] = '23f1f5fa5ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layer', 'last_part_received_utc')
    op.drop_column('layer', 'processing_has_started')
    op.drop_column('layer', 'processing_completed_successfully')
    op.drop_column('layer', 'parts')
    op.drop_column('layer', 'processing_message')
    op.drop_column('layer', 'upload_id')
    op.drop_column('layer', 'all_parts_received')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('all_parts_received', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('layer', sa.Column('upload_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('layer', sa.Column('processing_message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('layer', sa.Column('parts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('layer', sa.Column('processing_completed_successfully', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('layer', sa.Column('processing_has_started', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('layer', sa.Column('last_part_received_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
